---
title: "aDNA"
author: "Jennifer Blanc"
date: "2024-07-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Look at data

```{r}
df <- fread("../data/adnaSel/raw/all_populations_mles.txt")
head(df)
```

## Sample Individuals for GWAS panel 

Plot PC1 vs PC2 colored by self-identified ethnic background
```{r, warning=FALSE}
# Load data and combine
dfPCA <- fread("../endpoints/ukbb/whole_biobank.eigenvec.gz")
dfEB <- fread("../endpoints/ukbb/EthnicBackground_21000.txt")
df <- inner_join(dfPCA, dfEB)

# Use continental labels 
df <- df %>% mutate(continental = case_when(EthnicBackground_21000 %in% c(4, 4001, 4002, 4003) ~ "Africa", EthnicBackground_21000 %in% c(1, 1001, 1002, 1003) ~ "Europe", EthnicBackground_21000 %in% c(2, 2001, 2002, 2003, 2004) ~ "Mixed", EthnicBackground_21000 %in% c(3, 3001, 3002, 3003, 3004) ~ "Asia"))
```

```{r}
# Make PCA plot color based on self identified Ethnic background
ggplot(data = df, aes(x = PC1, y = PC2, color = continental)) + geom_point() + theme_classic(base_size = 14) + scale_color_manual(values = c("darkred", "navy", "goldenrod4", "gray50"), na.value = "gray70")
```

Use predefined sets 
```{r}
df <- df %>% mutate(POP = continental)

# Use all genotyped individuals 
dfALL <- df %>% select("#FID", "IID", "POP")
fwrite(dfALL,"../data/adnaSel/ids/gwas_ids/ALL.txt", row.names = F, col.names = T, quote = F, sep = "\t")

# Use only WBS 
WBS <- fread("../data/ukbb/WBS.ids")
dfWBS <- inner_join(df, WBS) %>% select("#FID", "IID", "POP")
fwrite(dfWBS,"../data/adnaSel/ids/gwas_ids/WBS.txt", row.names = F, col.names = T, quote = F, sep = "\t")
```

Use distance from WBS
```{r}
# Get average of WBS
dfWBS <- inner_join(df, WBS)
avgPC1 <- mean(dfWBS$PC1)
avgPC2 <- mean(dfWBS$PC2)

# Calculate from WBS centroid 
avgPC <- c(avgPC1, avgPC2)
df$distance <- sqrt(rowSums((df[, 3:4] - avgPC)^2))

# Plot distance
ggplot(data = df, aes(x = distance, y = PC1, color = POP)) + geom_point() + theme_classic(base_size = 14) + scale_color_manual(values = c("darkred", "navy", "goldenrod4", "gray50"), na.value = "gray70")
```

Sample equal distances from WBS centroid 
```{r}
set.seed(12)
# Sample GWAS panels
maxDist <- max(df$distance)
interval <- maxDist / 4
q1 <- interval
q2 <- interval * 2
q3 <- interval * 3
q4 <- interval * 4

## Sample everyone 
dfGWAS <- df %>% filter(distance <=  q4) %>% sample_n(10000) %>% select("#FID", "IID", "POP")
fwrite(dfGWAS,"../data/adnaSel/ids/gwas_ids/q4.txt", row.names = F, col.names = T, quote = F, sep = "\t")

## Sample q3
dfGWAS <- df %>% filter(distance <=  q3)%>% sample_n(10000) %>% select("#FID", "IID", "POP")
fwrite(dfGWAS,"../data/adnaSel/ids/gwas_ids/q3.txt", row.names = F, col.names = T, quote = F, sep = "\t")

## Sample q4
dfGWAS <- df %>% filter(distance <=  q2)%>% sample_n(10000) %>% select("#FID", "IID", "POP")
fwrite(dfGWAS,"../data/adnaSel/ids/gwas_ids/q2.txt", row.names = F, col.names = T, quote = F, sep = "\t")

## 1sr quartile
dfGWAS <- df %>% filter(distance <=  q1)%>% sample_n(10000) %>% select("#FID", "IID", "POP")
fwrite(dfGWAS,"../data/adnaSel/ids/gwas_ids/q1.txt", row.names = F, col.names = T, quote = F, sep = "\t")
```

