---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Data Analysis Pipeline  

### Overlap Statistics  

- $D$: variance along test axis $r^\top G^\top G r$  
- $\mathbb{E}[D] = M - 1$  
- $\hat{\sigma}^2_{D}$: jackknife estimation of var(D)  
- $p_{D}$: p-value for hypothesis test (does D differ from $\mathbb{E}[D]$)  
- $Z$: proportion of variance along test axis $\frac{D}{Tr\mathbf{K}}$  
- $Tr\mathbf{K} = (M-1)L$  
- $\hat{\sigma}^2_{FGr}$: jackknife estimate of entries of $\hat{F}_{Gr}$ across blocks $\frac{1}{M}\sum\limits_{i=1}^M \frac{B-1}{B} \sum\limits_{j=1}^B \left( \hat{F}_{Gr,i}^{-j} - \frac{1}{B} \sum\limits_{k=1}^K \hat{F}_{Gr,i}^{-k} \right)^2 $  
- $var(\hat{F}_{Gr})$: variance of entries of $\hat{F}_{Gr}$ $\frac{1}{M} \sum\limits_{i=1}^M \left(\hat{F}_{Gr,i} - \frac{1}{M} \sum\limits_{\ell = 1}^M \hat{F}_{Gr,\ell} \right)^2$  
- $error = \frac{\hat{\sigma}^2_{FGr}}{var(\hat{F}_{Gr})}$  
- $signal = 1 - error$  
- $\gamma_{F} = 1 - error^2$  
- $\hat{\beta}_{pc,i} = Cov(\hat{F}_{Gr}, \hat{U}_{i})$ (use even-odd chromosomes)  
- $\hat{\beta}_{i}^2$: variance in $\hat{F}_{Gr}$ explained by $PC_i$  
- $R^2_{K} = \sum_{K} \beta^2_i$  


## Results 

[Test Example](TestExample.html)  

- Contrasts are "African" vs "European" allele frequency differences in the UKBB  
- This analysis is used to check the pipeline output and as an interpretable example  

[SDS](SDS.html)  

- UK10K contrasts are from [Field et al. 2016](https://www.science.org/doi/10.1126/science.aag0776) 
- Han contrasts are from [Luo et al. 2023](https://www.sciencedirect.com/science/article/pii/S2095927323005558)  


[aDNA Selection](adnaSel.html)  

- Contrasts are from [Le et al. 2022](https://www.biorxiv.org/content/10.1101/2022.08.24.505188v1)
